#ifndef __GUI_frame_decode_B__
#define __GUI_frame_decode_B__

/**
@file
Subclass of frame_decode_B, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include "DrawManager.h"
#include "LoadSaveManager.h"
#include <memory>
#include <functional>
#include <stdexcept>
#include "Crypto.h"
#include "TextBoxLogger.h"
/** Implementing frame_decode_B */
class GUI_frame_decode_B : public frame_decode_B
{
	protected:
		// Handlers for frame_decode_B events.
		void frame_decode_B_OnUpdateUI( wxUpdateUIEvent& event );
		void button_load_input1_OnButtonClick( wxCommandEvent& event );
		void button_load_input2_OnButtonClick( wxCommandEvent& event );
		void button_decode_OnButtonClick( wxCommandEvent& event );
		void button_save_output_OnButtonClick( wxCommandEvent& event );
		void button_return_OnButtonClick( wxCommandEvent& event );

	public:
		/** Constructor */
		GUI_frame_decode_B( wxWindow* parent );
	//// end generated class members
		void RepaintAll();
	protected:
		std::shared_ptr<wxImage> inputImage1;
		std::shared_ptr<wxImage> inputImage2;
		std::shared_ptr<wxImage> outputImage;
		//void progress(int number, int all);
		TextBoxLogger _logger;


};

#endif // __GUI_frame_decode_B__
