#ifndef __GUI_frame_encode_AB__
#define __GUI_frame_encode_AB__

/**
@file
Subclass of frame_encode_AB, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <memory>
#include <chrono>
#include <thread>

#include "TextBoxLogger.h"
#include "DrawManager.h"
#include "LoadSaveManager.h"
#include "Crypto.h"
#include "TextBoxLogger.h"
#include "Stegano.h"

/** Implementing frame_encode_AB */
class GUI_frame_encode_AB : public frame_encode_AB
{
	protected:
		// Handlers for frame_encode_AB events.
		void frame_encode_AB_OnUpdateUI( wxUpdateUIEvent& event );
		void button_load_input_OnButtonClick( wxCommandEvent& event );
		void button_load_ref_OnButtonClick( wxCommandEvent& event );
		void button_encode_OnButtonClick( wxCommandEvent& event );
		void button_save_output1_OnButtonClick( wxCommandEvent& event );
		void button_save_output2_OnButtonClick( wxCommandEvent& event );
		void button_return_OnButtonClick( wxCommandEvent& event );

	public:
		/** Constructor */
		GUI_frame_encode_AB( wxWindow* parent );
	//// end generated class members
		void RepaintAll();

	protected:
		TextBoxLogger _logger;
		std::shared_ptr<wxImage> inputImage;
		std::shared_ptr<wxImage> referenceImage;
		std::shared_ptr<wxImage> outputImage1;
		std::shared_ptr<wxImage> outputImage2;
		




};

#endif // __GUI_frame_encode_AB__
