#ifndef __GUI_frame_encode_B__
#define __GUI_frame_encode_B__

/**
@file
Subclass of frame_encode_B, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <memory>
#include <functional>
#include <stdexcept>
#include "DrawManager.h"
#include "LoadSaveManager.h"
#include "Crypto.h"
#include "TextBoxLogger.h"

/** Implementing frame_encode_B */
class GUI_frame_encode_B : public frame_encode_B
{
	protected:
		// Handlers for frame_encode_B events.
		void frame_encode_B_OnUpdateUI( wxUpdateUIEvent& event );
		void button_load_input_OnButtonClick( wxCommandEvent& event );
		void button_encode_OnButtonClick( wxCommandEvent& event );
		void button_save_output1_OnButtonClick( wxCommandEvent& event );
		void button_save_output2_OnButtonClick( wxCommandEvent& event );
		void button_return_OnButtonClick( wxCommandEvent& event );

	public:
		/** Constructor */
		GUI_frame_encode_B( wxWindow* parent );
	//// end generated class members
		void RepaintAll();

	protected:
		std::shared_ptr<wxImage> inputImage;
		std::shared_ptr<wxImage> outputImage1;
		std::shared_ptr<wxImage> outputImage2;
		//void progress(int number, int all);	
		TextBoxLogger _logger;


};

#endif // __GUI_frame_encode_B__
